CREATE TABLE transaction (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  uuid VARCHAR(250) NOT NULL UNIQUE,
  card VARCHAR(250) NOT NULL,
  bank VARCHAR(250) DEFAULT NULL,
  amount INT DEFAULT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  type VARCHAR(250) DEFAULT NULL
);

CREATE TABLE balance (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  cardNumber VARCHAR(250) NOT NULL,
  amount INT DEFAULT NULL
);

CREATE INDEX idx_cardNumber ON balance (cardNumber);